[env:ATtiny1614]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
upload_protocol = custom
upload_port = /dev/cu.usbserial-001
upload_speed = 230400
build_flags = -DF_CPU=16000000L
upload_flags =
    -t
    uart
    -u
    $UPLOAD_PORT
    -b
    $UPLOAD_SPEED
    -d
    $BOARD
    --fuses
    "1:0b11100101 2:0x01 6:0x05 8:0x00"

upload_command = ~/.platformio/penv/bin/python3 -u ~/.platformio/packages/framework-arduino-megaavr-megatinycore/tools/prog.py $UPLOAD_FLAGS -f$SOURCE -a write
monitor_speed = 4800

; the fuse 8 is not sure
; Set fuses: ['0:0x00', '1:0b00000101', '2:0x01', '5:0b11000100', '6:0x05', '7:0x00', '8:0x02'] 1.8v enable BOD 16ms
; Set fuses: ['0:0x00', '1:0b11100101', '2:0x01', '5:0b11000100', '6:0x05', '7:0x00', '8:0x02'] 4.2 enables startup 16ms
; Set fuses: ['0:0x00', '1:0b11100101', '2:0x01', '5:0b11000100', '6:0x04', '7:0x00', '8:0x02'] 4.2 enabled startup 8ms
